apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3s40
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/lholmqui-tenant/nodejs-rest-http/devfile-sample-3s40@sha256:c8786e18eda3b32ec76f69d55890d3fec95c204decc121b0766bc81ad28f8dee
        name: my-nodejs
        resources: {}
status: {}
